sudo: required
dist: trusty

language: node_js

install:
  - gem install coveralls-lcov
  - "cp package.json /opt && npm install --prefix=/opt /opt"

script:
  - "/opt/node_modules/.bin/karma start tests/cover.conf.js"

after_success:
  - "coveralls-lcov coverage/lcov.info"
